id = "rust-axum"
name = "Rust Axum Plugin"
version = "0.0.0"
component = "${CARGO_TARGET_DIR:target}/wasm32-wasip2/debug/rust_axum.wasm"
endpoint = "/rust/axum/"

[build]
cmd = "cargo build --target wasm32-wasip2"
